# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InStaCloneSnapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InStaCloneSnapKit
    pod 'SnapKit', '~> 5.0.0'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'Firebase/Auth'
    pod 'ActiveLabel'
    pod 'SDWebImage', '~> 5.0'
    pod 'JGProgressHUD'
    pod 'YPImagePicker' 
end
